#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
  source "${ZDOTDIR:-$HOME}/.zprezto/zprezto-update-override.zsh"
fi

# Customize to your needs...

export LSCOLORS=ExfxcxdxbxGxDxabagacad
export HISTFILE=${ZDOTDIR:-$HOME}/.zhistory

# Initialise rbenv if it's installed.
if [[ $(command -v rbenv) ]]; then
  eval "$(rbenv init -)"
fi
